---
title: "HypeBeast Index Performance"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(tidyquant)
library(quantmod)
library(dplyr)
```
Column {.tabset .tabset-fade data-width=500}
-----------------------------------------------------------------------

### Highchart Performance

```{r}
rm(list=ls())
library(ggplot2)
library(tidyquant)
library(quantmod)
library(dplyr)
#------------------------------------------------------------
ticker <-c("0150.HK",
"1913.HK",
"2020.HK",
"2331.HK",
"NKE",
"VFC",
"ESLOF",
"FRCOY",
"IDEXF",
"KER.PA",
"MC.PA",
"RMS.PA",
"HM-B.ST",
"CFR.SW",
"ADS.DE",
"BRBY.L",
"MONC.MI",
"SFER.MI",
"COLM",
"FL",
"FTCH",
"GES",
"GIL",
"GPS",
"RL",
"TPR",
"UAA",
"UHR.SW",
"7936.T",
"PUM.DE"
)
#----------------------------------------------
df <-tq_get(get = "stock.prices",x=ticker, from="2019-01-01")
stock_returns_monthly <- df %>%
  group_by(symbol)%>%
  tq_transmute(., 
               select     = adjusted, 
                 mutate_fun = periodReturn, 
                 period     = "monthly", 
                 col_rename = "Ra")
#----------------------------------------------------------------
market_caps <- c(0.256,312,178,118,72.2,69.3,65.5,60.4,54.5,34.5,30.7,22.6,19.8,18.7,13.8,12.2,11.3,10.6,8.39,8.31,6.75,5.35,4.83,4.22,3.60,3.48,3.31,2.79,2.69,1.11 )%>%
  data.frame()
weights <-market_caps%>%
  mutate(weights = market_caps/sum(market_caps))
colnames(weights) <-c("Market_cap","weights")
wts <- weights$weights
w <-wts%>%zoo()%>%as.numeric()
#------------------------------------------------------------------------------------
portfolio_growth_monthly <- stock_returns_monthly %>%
    tq_portfolio(assets_col   = symbol, 
                 returns_col  = Ra, 
                 weights      = w, 
                 col_rename   = "investment.growth",
                 wealth.index = TRUE) %>%
    mutate(investment.growth = investment.growth * 1000)
#--------------------------------------------------------------------
portfolio_growth_monthly %>%
  ggplot(., mapping=aes(x=date, y=investment.growth))+
    geom_line(size = 2) +
    labs(title = "Portfolio Growth",
         subtitle = "Comparing Multiple Portfolios",
         x = "", y = "Portfolio Value",
         color = "Portfolio") +
    geom_smooth(method = "loess") +
    theme_tq() +
    scale_color_tq() +
    scale_y_continuous(labels = scales::dollar)

library(highcharter)
library(htmltools)
portfolio_growth_monthly %>%
  hchart(.,
         type="line",
         mapping=hcaes(x=as.Date(date), 
                       y=round(investment.growth,digits=2)))%>%
  hc_tooltip(pointFormat="<b>Portfolio Value:</b> ${point.y} <br>")%>%
  hc_title(text="Cumulative Growth of a $1000 Investment in HYPEBEAST Index",
           style=list(fontSize="16xp", fontWeight="bold"))%>%
  hc_subtitle(text="Equity-Weighted HypeBeast Index Portfolio")%>%
  hc_xAxis(title = list(text="Dates"))%>%
  hc_add_theme(hc_theme_google())%>%
  hc_colors(colors="#29485b")%>%
  hc_yAxis(title=list(text="Investment Growth"))%>%
  hc_plotOptions(series = list(animation = list(duration = 25000)))
```
### Market Indicator
```{r}
portfolio_growth_monthly %>%
  ggplot(., mapping=aes(x=date, y=investment.growth))+
    geom_line(size = 2) +
    labs(title = "Cumulative Growth of a $1000 Investment in Hypebeast Index",
         subtitle = "Investmade made in January 2019",
         x = "", y = "Portfolio Value",
         color = "Portfolio") +
    geom_smooth(method = "loess") +
    theme_tq() +
    scale_color_tq() +
    scale_y_continuous(labels = scales::dollar)

```


Column {data-width=500}
-----------------------------------------------------------------------

### Heatmap

```{r}
stock_returns_monthly$date <- as.Date(stock_returns_monthly$date)
data <-stock_returns_monthly%>%
  group_by(symbol)%>%
  filter(.,date==max(date))
library(ggplot2)
library(tidyverse)
library(hrbrthemes)
data%>%
  rename(Returns="Ra")%>%
  ggplot(., mapping=aes(symbol,symbol, fill= Returns)) + 
  geom_tile() +
  scale_fill_gradient(low="red", high="green") +
  theme_ipsum() + labs(title="Heatmap", subtitle="Heatmap depicts how high or low the return on stock is", x="Symbol", y="Symbol", caption="")
  
```

### Table

```{r}
library(gt)
tbl <- data.frame(data,wts)
tbl <- tbl%>%
  rename(Returns="Ra", 
         Weights=".", Symbol="symbol", Date="date")%>%
  arrange(desc(Weights))


div(style='height:600px; overflow-y: scroll', gt(tbl)%>%
      tab_header(title=strong("Main inputs"), 
                 subtitle=em("Monthly returns and their weights for each stock in the portfolio"))%>%
  tab_source_note(
    source_note = "Source: Yahoo Finance, 
    Hypebeast"
  )%>%
    fmt_percent(
    columns = c(Weights,Returns),
    decimals = 2
  )%>% 
  data_color(
    columns = Returns,
    colors = scales::col_numeric(
      palette = c(low="#ff4d4d", high="#64e764"),
      domain = NULL
    )
    )%>%
  cols_move(
    columns = vars(Returns),
    after = vars(Weights)
  )
)

```

